name: Deploy to Cloud Run

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PROJECT_ID: rss-yoriyori
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - run: TAG=${{ github.sha }} docker buildx bake --push
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - run: terraform -chdir=terraform init
      - run: |
          terraform -chdir=terraform apply \
            -var="project_id=${{ env.PROJECT_ID }}" \
            -var="image_tag=${{ github.sha }}" \
            -auto-approve
